// Training plan data for Jake & Emma
// Extracted to stay under GitHub file size limits

const T = {
  bark:"#1a1208",barkMid:"#2a1e0f",barkLight:"#3a2a18",
  moss:"#2d3d1a",mossLight:"#3d5422",canopy:"#4a6b2a",
  leaf:"#6b9c38",fern:"#8ab84a",sage:"#a8c87a",
  cream:"#f2ead8",parchment:"#e8dcbf",
  amber:"#c8843a",amberWarm:"#e09840",amberGlow:"#f0b060",
  dew:"#7ab8a0",dewDim:"#4a8870",rust:"#c05030",mist:"#8aaa78",
};

// === JAKE DATA ===
const JAKE_PHASES = [
  {id:"base",name:"Base Building",weeks:[1,2,3,4],label:"Phase 1",color:T.fern,icon:"🌱",focus:"Rebuild aerobic foundation",weeklyTargets:{cycling:{hours:"3–5 hrs",intensity:"Easy (Z2)",sessions:3},running:{hours:"30–60 min",intensity:"Run/walk",sessions:1},strength:{hours:"20–30 min",intensity:"Bodyweight",sessions:1}}},
  {id:"build",name:"Build",weeks:[5,6,7,8],label:"Phase 2",color:T.amberWarm,icon:"🔥",focus:"Add intensity & extend endurance",weeklyTargets:{cycling:{hours:"5–7 hrs",intensity:"Z2 + tempo",sessions:3},running:{hours:"45–75 min",intensity:"Easy + trail",sessions:1},strength:{hours:"25–35 min",intensity:"Bodyweight + bands",sessions:1}}},
  {id:"peak",name:"Peak Performance",weeks:[9,10,11,12],label:"Phase 3",color:T.rust,icon:"⚡",focus:"Sustained efforts & climbing",weeklyTargets:{cycling:{hours:"6–9 hrs",intensity:"Z2 + sweet spot",sessions:"3–4"},running:{hours:"60–90 min",intensity:"Easy + trail",sessions:"1–2"},strength:{hours:"20–30 min",intensity:"Maintenance",sessions:1}}},
];
const JAKE_WEEKS = [
  {week:1,phase:"base",theme:"Ease back in",totalHours:"3.5 hrs",days:[{day:"Monday",type:"cycle",label:"Easy Spin",duration:"45 min",zone:"Z2",route:"Swamp Rabbit Trail",details:"Flat route, cadence 85–95 RPM."},{day:"Tuesday",type:"rest",label:"Rest / Walk",duration:"–",zone:"–",route:"–",details:"Rest or 20-min walk."},{day:"Wednesday",type:"run",label:"Run/Walk Intervals",duration:"25 min",zone:"Z1–Z2",route:"SRT (TR)",details:"5 min walk → 8×(2 min jog / 1 min walk) → cool-down."},{day:"Thursday",type:"cycle",label:"Easy Ride",duration:"60 min",zone:"Z2",route:"SRT toward Greenville",details:"Flat to rolling. Practice fueling."},{day:"Friday",type:"rest",label:"Rest Day",duration:"–",zone:"–",route:"–",details:"Complete rest."},{day:"Saturday",type:"cycle",label:"Longer Easy Ride",duration:"75 min",zone:"Z2",route:"SRT extended",details:"Longest ride of the week."},{day:"Sunday",type:"strength",label:"Bodyweight + Mobility",duration:"25 min",zone:"–",route:"Home",details:"Squats, lunges, plank, glute bridges, calf raises. 10 min stretch."}]},
  {week:2,phase:"base",theme:"Build rhythm",totalHours:"4 hrs",days:[{day:"Monday",type:"cycle",label:"Easy Spin",duration:"50 min",zone:"Z2",route:"Furman / Cherrydale",details:"Rolling terrain. Smooth cadence."},{day:"Tuesday",type:"rest",label:"Active Recovery",duration:"–",zone:"–",route:"–",details:"Walk or easy 15 min spin."},{day:"Wednesday",type:"run",label:"Run/Walk Progression",duration:"28 min",zone:"Z1–Z2",route:"SRT (TR)",details:"Slightly longer jog intervals."},{day:"Thursday",type:"cycle",label:"Easy Ride",duration:"65 min",zone:"Z2",route:"SRT",details:"Cadence targets 85–95 RPM."},{day:"Friday",type:"rest",label:"Rest Day",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"cycle",label:"Long Easy Ride",duration:"90 min",zone:"Z2",route:"SRT — TR to Greenville",details:"Eat/drink every 30 min."},{day:"Sunday",type:"strength",label:"Bodyweight + Mobility",duration:"30 min",zone:"–",route:"Home",details:"Goblet squats, reverse lunges, push-ups, plank, yoga flow."}]},
  {week:3,phase:"base",theme:"First real volume week",totalHours:"4.5 hrs",days:[{day:"Monday",type:"cycle",label:"Easy Ride",duration:"55 min",zone:"Z2",route:"Furman / Cherrydale",details:"Focus on breathing rhythm."},{day:"Tuesday",type:"rest",label:"Rest / Walk",duration:"–",zone:"–",route:"–",details:"20–30 min walk or full rest."},{day:"Wednesday",type:"run",label:"Continuous Easy Run",duration:"25 min",zone:"Z2",route:"SRT or Lake Conestee",details:"First continuous run!"},{day:"Thursday",type:"cycle",label:"Easy + Cadence",duration:"70 min",zone:"Z2",route:"SRT",details:"2-min cadence drills at 100+ RPM every 15 min."},{day:"Friday",type:"rest",label:"Rest Day",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"cycle",label:"Long Easy Ride",duration:"105 min",zone:"Z2",route:"SRT extended or Altamont",details:"~1h45m. 30g carbs/hour."},{day:"Sunday",type:"strength",label:"Strength + Core",duration:"30 min",zone:"–",route:"Home",details:"Single-leg squats, push-ups, side plank, band pull-aparts."}]},
  {week:4,phase:"base",theme:"Recovery week",totalHours:"3.5 hrs",days:[{day:"Monday",type:"cycle",label:"Recovery Spin",duration:"40 min",zone:"Z1–Z2",route:"Flat — SRT",details:"Very easy step-back."},{day:"Tuesday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Wednesday",type:"run",label:"Easy Run",duration:"25 min",zone:"Z2",route:"SRT",details:"Same as last week — recovery."},{day:"Thursday",type:"cycle",label:"Easy Ride",duration:"50 min",zone:"Z2",route:"Furman / Cherrydale",details:"Relaxed ride."},{day:"Friday",type:"rest",label:"Rest Day",duration:"–",zone:"–",route:"–",details:"Rest. Phase 2 next."},{day:"Saturday",type:"cycle",label:"Moderate Ride",duration:"75 min",zone:"Z2",route:"SRT",details:"Stay easy."},{day:"Sunday",type:"strength",label:"Mobility Focus",duration:"25 min",zone:"–",route:"Home",details:"Light circuit + 15 min stretching."}]},
  {week:5,phase:"build",theme:"First tempo work",totalHours:"5.5 hrs",days:[{day:"Monday",type:"cycle",label:"Easy Ride",duration:"60 min",zone:"Z2",route:"SRT",details:"Fresh from recovery week."},{day:"Tuesday",type:"rest",label:"Active Recovery",duration:"–",zone:"–",route:"–",details:"Easy walk or foam rolling."},{day:"Wednesday",type:"cycle",label:"Tempo Intervals ⚡",duration:"55 min",zone:"Z2–Z3",route:"SRT (flat)",details:"4×5 min tempo w/ 3 min easy."},{day:"Thursday",type:"run",label:"Easy Trail Run",duration:"30 min",zone:"Z2",route:"Furman or Lake Conestee",details:"First trail run!"},{day:"Friday",type:"rest",label:"Rest Day",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"cycle",label:"Long Ride + Rollers",duration:"2 hrs",zone:"Z2",route:"Altamont or SRT extended",details:"40g carbs/hour."},{day:"Sunday",type:"strength",label:"Cyclist Strength",duration:"30 min",zone:"–",route:"Home",details:"Bulgarian split squats, push-ups, banded side walks, single-leg RDL."}]},
  {week:6,phase:"build",theme:"Extending tempo",totalHours:"6 hrs",days:[{day:"Monday",type:"cycle",label:"Easy Ride",duration:"60 min",zone:"Z2",route:"Furman / Cherrydale",details:"Recovery from weekend."},{day:"Tuesday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Wednesday",type:"cycle",label:"Tempo Intervals ⚡",duration:"60 min",zone:"Z2–Z3",route:"SRT",details:"3×8 min tempo w/ 3 min easy."},{day:"Thursday",type:"run",label:"Trail Run w/ Hills",duration:"35 min",zone:"Z2–Z3",route:"Paris Mountain (lower)",details:"Walk steep climbs, run flats."},{day:"Friday",type:"rest",label:"Rest Day",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"cycle",label:"Long Ride",duration:"2 hrs 15 min",zone:"Z2",route:"SRT extended or Altamont",details:"Fuel every 30 min."},{day:"Sunday",type:"strength",label:"Strength + Core",duration:"30 min",zone:"–",route:"Home",details:"Step-ups, diamond push-ups, banded clamshells, plank."}]},
  {week:7,phase:"build",theme:"Sweet spot introduction",totalHours:"6.5 hrs",days:[{day:"Monday",type:"cycle",label:"Easy Ride",duration:"60 min",zone:"Z2",route:"SRT",details:"Monday base miles."},{day:"Tuesday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Wednesday",type:"cycle",label:"Sweet Spot ⚡",duration:"65 min",zone:"Z3–Z4",route:"Altamont or SRT",details:"2×12 min sweet spot w/ 5 min easy."},{day:"Thursday",type:"run",label:"Trail Run",duration:"40 min",zone:"Z2",route:"Paris Mountain",details:"Longer trail run. Walk steep sections."},{day:"Friday",type:"rest",label:"Rest Day",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"cycle",label:"Long Ride",duration:"2 hrs 30 min",zone:"Z2",route:"Caesars Head approach (partial)",details:"Save full climb for Phase 3."},{day:"Sunday",type:"strength",label:"Cyclist Strength",duration:"30 min",zone:"–",route:"Home",details:"Goblet squats, pause push-ups, calf raises, hollow body."}]},
  {week:8,phase:"build",theme:"Recovery week",totalHours:"4.5 hrs",days:[{day:"Monday",type:"cycle",label:"Recovery Spin",duration:"45 min",zone:"Z1–Z2",route:"Flat — SRT",details:"Very easy step-back."},{day:"Tuesday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Wednesday",type:"cycle",label:"Easy + Openers",duration:"50 min",zone:"Z2",route:"Furman / Cherrydale",details:"3×30-sec pick-ups."},{day:"Thursday",type:"run",label:"Easy Run",duration:"30 min",zone:"Z2",route:"SRT or Lake Conestee",details:"Easy flat run."},{day:"Friday",type:"rest",label:"Rest Day",duration:"–",zone:"–",route:"–",details:"Rest. Peak phase next."},{day:"Saturday",type:"cycle",label:"Moderate Ride",duration:"90 min",zone:"Z2",route:"SRT",details:"Shorter than recent Saturdays."},{day:"Sunday",type:"strength",label:"Mobility + Light",duration:"25 min",zone:"–",route:"Home",details:"Light circuit + stretching."}]},
  {week:9,phase:"peak",theme:"Climbing focus begins",totalHours:"7 hrs",days:[{day:"Monday",type:"cycle",label:"Easy Ride",duration:"60 min",zone:"Z2",route:"SRT",details:"Monday base miles."},{day:"Tuesday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Wednesday",type:"cycle",label:"Hill Repeats ⚡",duration:"70 min",zone:"Z3–Z5",route:"Altamont or Paris Mtn",details:"5×4 min climbing repeats."},{day:"Thursday",type:"run",label:"Trail Run w/ Hills",duration:"45 min",zone:"Z2–Z3",route:"Paris Mountain (full loop)",details:"Run the runnable, power-hike the steep."},{day:"Friday",type:"rest",label:"Rest Day",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"cycle",label:"Long Ride w/ Climbing",duration:"2 hrs 45 min",zone:"Z2–Z3",route:"Caesars Head or Altamont",details:"Fuel 40–50g carbs/hour."},{day:"Sunday",type:"strength",label:"Maintenance",duration:"25 min",zone:"–",route:"Home",details:"Squats, push-ups, plank, glute bridges."}]},
  {week:10,phase:"peak",theme:"Sustained efforts",totalHours:"7.5 hrs",days:[{day:"Monday",type:"cycle",label:"Easy Ride",duration:"60 min",zone:"Z2",route:"SRT",details:"Easy spin to recover."},{day:"Tuesday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Wednesday",type:"cycle",label:"Sweet Spot ⚡",duration:"75 min",zone:"Z3–Z4",route:"SRT or Altamont",details:"2×15 min sweet spot w/ 5 min easy."},{day:"Thursday",type:"run",label:"Trail + Strides",duration:"45 min",zone:"Z2–Z3",route:"Paris Mountain or Furman",details:"40 min trail + 4×20-sec strides."},{day:"Friday",type:"rest",label:"Rest Day",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"cycle",label:"Century Prep Ride",duration:"3 hrs",zone:"Z2–Z3",route:"Hwy 276 or Caesars Head",details:"Biggest ride of the plan!"},{day:"Sunday",type:"strength",label:"Maintenance",duration:"25 min",zone:"–",route:"Home",details:"Same as Week 9."}]},
  {week:11,phase:"peak",theme:"Peak volume — biggest week",totalHours:"8 hrs",days:[{day:"Monday",type:"cycle",label:"Easy Ride",duration:"65 min",zone:"Z2",route:"SRT",details:"Recovery spin."},{day:"Tuesday",type:"run",label:"Easy Trail Run",duration:"35 min",zone:"Z2",route:"Lake Conestee or Furman",details:"Second run day. Flat and easy."},{day:"Wednesday",type:"cycle",label:"Over-Unders ⚡",duration:"75 min",zone:"Z3–Z5",route:"Altamont or flat",details:"4×(3 min below + 2 min above threshold)."},{day:"Thursday",type:"run",label:"Trail Run w/ Tempo",duration:"50 min",zone:"Z2–Z3",route:"Paris Mountain",details:"Longest trail run! 10 min tempo."},{day:"Friday",type:"rest",label:"Rest Day",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"cycle",label:"Long Endurance",duration:"3 hrs",zone:"Z2",route:"Hwy 276 or big loop",details:"All endurance — time in saddle."},{day:"Sunday",type:"rest",label:"Extra Rest",duration:"–",zone:"–",route:"–",details:"Replacing strength with rest."}]},
  {week:12,phase:"peak",theme:"Deload — you're back 🎉",totalHours:"4 hrs",days:[{day:"Monday",type:"cycle",label:"Easy Spin",duration:"45 min",zone:"Z1–Z2",route:"SRT",details:"Very easy. Absorb 11 weeks."},{day:"Tuesday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Wednesday",type:"cycle",label:"Easy + Openers",duration:"50 min",zone:"Z2",route:"Furman / Cherrydale",details:"4×30-sec brisk efforts."},{day:"Thursday",type:"run",label:"Fun Trail Run",duration:"35 min",zone:"Z2",route:"Your favorite trail",details:"No pace goals. Just enjoy."},{day:"Friday",type:"rest",label:"Rest Day",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"cycle",label:"Celebration Ride 🎉",duration:"90 min",zone:"Z2",route:"Your favorite route",details:"You're back!"},{day:"Sunday",type:"strength",label:"Mobility + Reflection",duration:"20 min",zone:"–",route:"Home",details:"Light circuit + stretching."}]},
];

// === EMMA DATA ===
const EMMA_PHASES = [
  {id:"sharpening",name:"10K Sharpening",weeks:[1,2],label:"Phase 1",color:T.fern,icon:"🎯",focus:"Sharpen for April 14 10K",weeklyTargets:{running:{hours:"2.5–3 hrs",intensity:"Easy + 1 quality",sessions:3},cycling:{hours:"Commute if nice",intensity:"Easy",sessions:"0–2"},yoga:{hours:"1–2 sessions",intensity:"Gentle / mobility",sessions:"1–2"}}},
  {id:"base",name:"Half Marathon Base Build",weeks:[3,4,5,6],label:"Phase 2",color:"#7ab8d8",icon:"🏗️",focus:"Build mileage toward half marathon",weeklyTargets:{running:{hours:"3.5–5 hrs",intensity:"Easy + 1 tempo",sessions:3},cycling:{hours:"Commute + optional",intensity:"Easy to moderate",sessions:"1–2"},yoga:{hours:"1 session",intensity:"Strength-focused",sessions:1}}},
  {id:"build",name:"Half #1 Race & Recovery → Build",weeks:[7,8,9,10],label:"Phase 3",color:T.amberWarm,icon:"🔥",focus:"Race Half #1, recover, build for goal race",weeklyTargets:{running:{hours:"3–5.5 hrs",intensity:"Race → Recovery → Quality",sessions:"3–4"},cycling:{hours:"Commute + weekend",intensity:"Easy to moderate",sessions:"1–2"},yoga:{hours:"1–2 sessions",intensity:"Recovery → strength",sessions:"1–2"}}},
  {id:"peak",name:"Peak & Taper — Goal Race",weeks:[11,12,13,14],label:"Phase 4",color:T.rust,icon:"⚡",focus:"Peak fitness, taper for June goal half",weeklyTargets:{running:{hours:"4–6 hrs → 2 hrs",intensity:"Quality → taper",sessions:"3–4"},cycling:{hours:"Easy commutes in taper",intensity:"Easy",sessions:"0–1"},yoga:{hours:"1–2 sessions",intensity:"Strength → gentle",sessions:"1–2"}}},
];
const EMMA_RACES = [
  {name:"10K",date:"April 14",goal:"Feel strong, finish confident",color:T.fern},
  {name:"Half Marathon #1",date:"May 9",goal:"Finish strong — not all-out",color:T.amberWarm},
  {name:"Half #2 (GOAL)",date:"June TBD",goal:"PR effort — leave it all out there",color:T.rust},
];
const EMMA_WEEKS = [
  {week:1,phase:"sharpening",theme:"Tune up — stay fresh",totalHours:"3.5 hrs",totalMiles:"~10 mi",days:[{day:"Monday",type:"run",label:"Easy Run",duration:"30 min",zone:"Z2",route:"SRT (TR)",details:"2.5–3 miles conversational."},{day:"Tuesday",type:"yoga",label:"Yoga / Pilates",duration:"45 min",zone:"–",route:"Studio or home",details:"Pilates core or vinyasa flow."},{day:"Wednesday",type:"run",label:"10K Pace Intervals ⚡",duration:"35 min",zone:"Z3–Z4",route:"SRT (flat)",details:"4×3 min at 10K pace w/ 2 min easy."},{day:"Thursday",type:"cycle",label:"Bike Commute",duration:"45–60 min",zone:"Z2",route:"SRT to work",details:"Easy ride. Zero impact volume."},{day:"Friday",type:"rest",label:"Rest Day",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"run",label:"Long Run",duration:"50 min",zone:"Z2",route:"SRT",details:"4.5–5 miles easy."},{day:"Sunday",type:"rest",label:"Rest / Walk",duration:"–",zone:"–",route:"–",details:"Rest or 20-min walk."}]},
  {week:2,phase:"sharpening",theme:"🏁 10K Race Week (Apr 14)",totalHours:"2.5 hrs + race",totalMiles:"~8 mi + 10K",days:[{day:"Monday",type:"run",label:"Easy Shakeout",duration:"20 min",zone:"Z1–Z2",route:"SRT",details:"1.5–2 miles very easy."},{day:"Tuesday",type:"yoga",label:"Gentle Yoga",duration:"30 min",zone:"–",route:"Home",details:"Gentle flow — hip openers, breathing."},{day:"Wednesday",type:"run",label:"Openers",duration:"25 min",zone:"Z2 + strides",route:"SRT",details:"15 min easy + 4×20-sec strides."},{day:"Thursday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest. Race prep."},{day:"Friday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest or walk."},{day:"Saturday",type:"run",label:"Optional Shakeout",duration:"15 min",zone:"Z1",route:"Near race venue",details:"Optional easy jog + strides."},{day:"Sunday",type:"race",label:"🏁 10K RACE DAY",duration:"Race",zone:"Race effort",route:"Race course",details:"Start conservative. Push miles 5–6. Feel strong!"}]},
  {week:3,phase:"base",theme:"Post-10K → start building",totalHours:"3.5 hrs",totalMiles:"~12 mi",days:[{day:"Monday",type:"rest",label:"Post-Race Rest",duration:"–",zone:"–",route:"–",details:"Recovery from 10K."},{day:"Tuesday",type:"run",label:"Recovery Run",duration:"25 min",zone:"Z1–Z2",route:"SRT or Lake Conestee",details:"Very easy shakeout."},{day:"Wednesday",type:"yoga",label:"Pilates",duration:"45 min",zone:"–",route:"Studio or home",details:"Core and glute activation."},{day:"Thursday",type:"run",label:"Easy Run",duration:"35 min",zone:"Z2",route:"SRT",details:"3–3.5 miles easy."},{day:"Friday",type:"cycle",label:"Bike Commute",duration:"45–60 min",zone:"Z2",route:"SRT to work",details:"Impact-free volume."},{day:"Saturday",type:"run",label:"Long Run",duration:"55 min",zone:"Z2",route:"SRT",details:"~5 miles. New baseline."},{day:"Sunday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."}]},
  {week:4,phase:"base",theme:"Mileage bump — long run grows",totalHours:"4 hrs",totalMiles:"~15 mi",days:[{day:"Monday",type:"run",label:"Easy Run",duration:"30 min",zone:"Z2",route:"SRT (TR)",details:"3 miles easy."},{day:"Tuesday",type:"yoga",label:"Pilates Strength",duration:"45 min",zone:"–",route:"Studio or home",details:"Single-leg stability, core."},{day:"Wednesday",type:"run",label:"Tempo Run ⚡",duration:"40 min",zone:"Z2–Z3",route:"SRT (flat)",details:"20 min tempo in the middle."},{day:"Thursday",type:"cycle",label:"Bike Commute",duration:"45–60 min",zone:"Z2",route:"SRT to work",details:"Easy commute."},{day:"Friday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"run",label:"Long Run",duration:"65 min",zone:"Z2",route:"SRT extended",details:"~6 miles. Fuel at mile 4."},{day:"Sunday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."}]},
  {week:5,phase:"base",theme:"Building the engine",totalHours:"4.5 hrs",totalMiles:"~18 mi",days:[{day:"Monday",type:"run",label:"Easy Run",duration:"35 min",zone:"Z2",route:"SRT",details:"3.5 miles easy."},{day:"Tuesday",type:"yoga",label:"Hot Yoga or Pilates",duration:"50 min",zone:"–",route:"Studio",details:"Hot yoga or hip strength."},{day:"Wednesday",type:"run",label:"Tempo + Cruise ⚡",duration:"45 min",zone:"Z3",route:"SRT (flat)",details:"3×7 min tempo w/ 2 min easy."},{day:"Thursday",type:"cycle",label:"Bike Commute",duration:"50–70 min",zone:"Z2",route:"SRT to work",details:"Easy commute."},{day:"Friday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"run",label:"Long Run",duration:"75 min",zone:"Z2",route:"SRT — TR toward GVL",details:"~7.5 miles. Longest yet!"},{day:"Sunday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."}]},
  {week:6,phase:"base",theme:"Step-back before Half #1",totalHours:"3.5 hrs",totalMiles:"~13 mi",days:[{day:"Monday",type:"run",label:"Easy Run",duration:"30 min",zone:"Z2",route:"SRT",details:"3 miles easy. Step-back."},{day:"Tuesday",type:"yoga",label:"Gentle Yoga",duration:"40 min",zone:"–",route:"Studio or home",details:"Restorative."},{day:"Wednesday",type:"run",label:"Easy + Strides",duration:"30 min",zone:"Z2",route:"SRT",details:"25 min easy + 4×20-sec strides."},{day:"Thursday",type:"cycle",label:"Easy Commute",duration:"45 min",zone:"Z1–Z2",route:"SRT",details:"Active recovery only."},{day:"Friday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"run",label:"Long Run (Step-Back)",duration:"60 min",zone:"Z2",route:"SRT",details:"5.5–6 miles — shorter on purpose."},{day:"Sunday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."}]},
  {week:7,phase:"build",theme:"🏁 Half #1 Race Week (May 9)",totalHours:"2.5 hrs + race",totalMiles:"~8 mi + 13.1",days:[{day:"Monday",type:"run",label:"Easy Shakeout",duration:"25 min",zone:"Z1–Z2",route:"SRT",details:"2–2.5 miles very easy."},{day:"Tuesday",type:"yoga",label:"Gentle Yoga",duration:"30 min",zone:"–",route:"Home",details:"Hip openers, breathing."},{day:"Wednesday",type:"run",label:"Openers",duration:"25 min",zone:"Z2 + strides",route:"SRT",details:"15 min easy + 4×20-sec strides."},{day:"Thursday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest. Race prep."},{day:"Friday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest or walk."},{day:"Saturday",type:"run",label:"Optional Shakeout",duration:"15 min",zone:"Z1",route:"Near race venue",details:"Optional easy jog."},{day:"Sunday",type:"race",label:"🏁 HALF MARATHON #1",duration:"Race",zone:"Strong but controlled",route:"Race course",details:"Start conservative. NOT your goal race — finish strong."}]},
  {week:8,phase:"build",theme:"Post-half recovery",totalHours:"2.5 hrs",totalMiles:"~8 mi",days:[{day:"Monday",type:"rest",label:"Full Rest",duration:"–",zone:"–",route:"–",details:"Celebrate! You did a half marathon."},{day:"Tuesday",type:"yoga",label:"Gentle Yoga",duration:"30 min",zone:"–",route:"Home",details:"Restorative flow only."},{day:"Wednesday",type:"run",label:"Easy Shakeout",duration:"20 min",zone:"Z1",route:"SRT",details:"Walk/jog. Don't force it."},{day:"Thursday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Friday",type:"cycle",label:"Easy Spin",duration:"30 min",zone:"Z1",route:"SRT",details:"Zero impact recovery."},{day:"Saturday",type:"run",label:"Easy Run",duration:"30 min",zone:"Z2",route:"SRT",details:"First real run post-race."},{day:"Sunday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."}]},
  {week:9,phase:"build",theme:"Quality returns",totalHours:"4.5 hrs",totalMiles:"~16 mi",days:[{day:"Monday",type:"run",label:"Easy Run",duration:"35 min",zone:"Z2",route:"SRT",details:"3.5 miles easy."},{day:"Tuesday",type:"yoga",label:"Pilates Strength",duration:"45 min",zone:"–",route:"Studio",details:"Core + glute strength."},{day:"Wednesday",type:"run",label:"Tempo Run ⚡",duration:"45 min",zone:"Z3",route:"SRT (flat)",details:"2×10 min tempo w/ 3 min easy."},{day:"Thursday",type:"cycle",label:"Bike Commute",duration:"50 min",zone:"Z2",route:"SRT",details:"Easy impact-free volume."},{day:"Friday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"run",label:"Long Run",duration:"70 min",zone:"Z2",route:"SRT extended",details:"~7 miles. Rebuilding."},{day:"Sunday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."}]},
  {week:10,phase:"build",theme:"Biggest pre-taper week",totalHours:"5.5 hrs",totalMiles:"~20 mi",days:[{day:"Monday",type:"run",label:"Easy Run",duration:"40 min",zone:"Z2",route:"SRT",details:"4 miles easy."},{day:"Tuesday",type:"yoga",label:"Hot Yoga",duration:"50 min",zone:"–",route:"Studio",details:"Deep stretch + mental prep."},{day:"Wednesday",type:"run",label:"Goal Pace Work ⚡",duration:"50 min",zone:"Z3–Z4",route:"SRT (flat)",details:"3×8 min at goal half pace w/ 3 min easy."},{day:"Thursday",type:"cycle",label:"Easy Ride",duration:"50 min",zone:"Z2",route:"SRT",details:"Impact-free volume."},{day:"Friday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"run",label:"Long Run",duration:"85 min",zone:"Z2",route:"SRT — TR to GVL",details:"~8.5 miles! Longest run ever."},{day:"Sunday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."}]},
  {week:11,phase:"peak",theme:"Peak volume",totalHours:"5.5 hrs",totalMiles:"~22 mi",days:[{day:"Monday",type:"run",label:"Easy Run",duration:"40 min",zone:"Z2",route:"SRT",details:"4 miles easy."},{day:"Tuesday",type:"yoga",label:"Pilates",duration:"45 min",zone:"–",route:"Studio",details:"Strength + stability."},{day:"Wednesday",type:"run",label:"Race Simulation ⚡",duration:"55 min",zone:"Z3–Z4",route:"SRT (flat)",details:"2×12 min at goal pace w/ 4 min easy."},{day:"Thursday",type:"run",label:"Easy Recovery",duration:"25 min",zone:"Z1–Z2",route:"SRT",details:"Shake out from yesterday."},{day:"Friday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"run",label:"Long Run",duration:"95 min",zone:"Z2",route:"SRT extended",details:"~10 miles! Peak long run."},{day:"Sunday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Full rest. Taper starts."}]},
  {week:12,phase:"peak",theme:"Taper begins",totalHours:"4 hrs",totalMiles:"~15 mi",days:[{day:"Monday",type:"run",label:"Easy Run",duration:"35 min",zone:"Z2",route:"SRT",details:"3.5 miles. Feeling fresh."},{day:"Tuesday",type:"yoga",label:"Gentle Yoga",duration:"30 min",zone:"–",route:"Home",details:"Restorative. Mental prep."},{day:"Wednesday",type:"run",label:"Sharpener ⚡",duration:"40 min",zone:"Z3",route:"SRT",details:"4×4 min at goal pace w/ 2 min easy."},{day:"Thursday",type:"cycle",label:"Easy Spin",duration:"30 min",zone:"Z1",route:"SRT",details:"Zero impact. Stay loose."},{day:"Friday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"run",label:"Long Run (Taper)",duration:"60 min",zone:"Z2",route:"SRT",details:"~6 miles. Shorter on purpose."},{day:"Sunday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."}]},
  {week:13,phase:"peak",theme:"Race week prep",totalHours:"2 hrs",totalMiles:"~7 mi",days:[{day:"Monday",type:"run",label:"Easy Shakeout",duration:"25 min",zone:"Z1–Z2",route:"SRT",details:"2 miles. Absorb the training."},{day:"Tuesday",type:"yoga",label:"Gentle Yoga",duration:"25 min",zone:"–",route:"Home",details:"Light movement only."},{day:"Wednesday",type:"run",label:"Openers",duration:"20 min",zone:"Z2 + strides",route:"SRT",details:"10 min easy + 4×20-sec strides."},{day:"Thursday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest. Race prep."},{day:"Friday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest. Hydrate. Carb up."},{day:"Saturday",type:"run",label:"Optional Shakeout",duration:"10 min",zone:"Z1",route:"Near venue",details:"Optional very easy jog."},{day:"Sunday",type:"rest",label:"Final Rest",duration:"–",zone:"–",route:"–",details:"Race tomorrow. You're ready."}]},
  {week:14,phase:"peak",theme:"🏁 GOAL RACE WEEK",totalHours:"Race!",totalMiles:"13.1!",days:[{day:"Monday",type:"race",label:"🏁 GOAL HALF MARATHON",duration:"Race",zone:"ALL OUT",route:"Race course",details:"THIS IS IT. Start smart, build through miles 5–10, empty the tank miles 11–13. You earned this."},{day:"Tuesday",type:"rest",label:"Celebrate!",duration:"–",zone:"–",route:"–",details:"You're a half marathoner (×2). Rest and recover."},{day:"Wednesday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Thursday",type:"yoga",label:"Gentle Yoga",duration:"20 min",zone:"–",route:"Home",details:"Light recovery flow."},{day:"Friday",type:"rest",label:"Rest",duration:"–",zone:"–",route:"–",details:"Rest."},{day:"Saturday",type:"run",label:"Easy Shakeout",duration:"20 min",zone:"Z1",route:"SRT",details:"First easy run back. Celebrate the journey."},{day:"Sunday",type:"rest",label:"Plan What's Next!",duration:"–",zone:"–",route:"–",details:"Rest. Reflect. What's the next goal?"}]},
];

export const ATHLETES = [
  {key:"jake",name:"Jake",emoji:"🚴",accent:"#7ab8d8",subtitle:"12-Week Cycling & Running Comeback",phases:JAKE_PHASES,weeks:JAKE_WEEKS,races:null},
  {key:"emma",name:"Emma",emoji:"🏃‍♀️",accent:T.rust,subtitle:"10K → Half → Goal Half Marathon",phases:EMMA_PHASES,weeks:EMMA_WEEKS,races:EMMA_RACES},
];
